---
- name: Ensure traefik data directory exist
  become: true
  file:
    group: "{{ traefik_group }}"
    owner: "{{ traefik_user }}"
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ traefik_dir }}"
    - "{{ traefik_acme_dir }}"
    - "{{ traefik_log_dir }}"

- name: Copy files
  become: true
  template:
    dest: "{{ traefik_dir }}/traefik.yml"
    group: "{{ traefik_group }}"
    owner: "{{ traefik_user }}"
    src: "templates/traefik.yml.j2"
  when: traefik_state == "started"

- name: Setup logrotate
  become: true
  blockinfile:
    path: "/etc/logrotate.d/traefik"
    block: |
      /{{ traefik_log_dir }}/traefik/*.log {
        compress
        create
        daily
        dateext
        dateformat -%Y%m%d
        missingok
        notifempty
        postrotate
          docker kill --signal="USR1" {{ traefik_container_name }}
        endscript
        rotate 5
      } 
    create: true

- name: Start traefik
  command: docker-compose -f traefik.yml up -d
  args:
    chdir: "{{ traefik_dir }}"
  when: traefik_state == "started"

- name: Stop traefik
  command: docker-compose -f traefik.yml down
  args:
    chdir: "{{ traefik_dir }}"
  when: traefik_state == "stopped"
