---
- name: Make sure that the traefik directory exists
  become: true
  file:
    group: "{{ traefik_group }}"
    owner: "{{ traefik_user }}"
    path: "{{ traefik_dir }}"
    state: directory
    mode: "0744"

- name: Copy traefik config
  become: yes
  become_user: "{{ traefik_user }}"
  template:
    dest: "{{ traefik_dir }}/traefik.toml"
    src: templates/traefik.toml.j2

- name: Copy acme.json
  become: yes
  become_user: "{{ traefik_user }}"
  copy:
    dest: "{{ traefik_dir }}/acme.json"
    force: no
    mode: 0600
    src: files/acme.json

- name: Create network
  become: yes
  become_user: "{{ traefik_user }}"
  docker_network:
    driver: bridge
    name: "{{ traefik_network }}"

- name: Run traefik proxy
  become: yes
  become_user: "{{ traefik_user }}"
  docker_container:
    image: traefik:latest
    name: traefik
    networks:
      - name: "{{ traefik_network }}"
    pull: true
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    recreate: true
    restart_policy: always
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml"
      - "{{ traefik_dir }}/acme.json:/etc/traefik/acme.json"
