---
- name: Ensure traefik data directory exist
  become: true
  file:
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ deploy_dir }}"
    - "{{ log_dir }}"

- name: Copy files
  become: true
  template:
    dest: "{{ deploy_dir }}/traefik.yml"
    group: "{{ deploy_group }}"
    owner: "{{ deploy_user }}"
    src: "templates/traefik.yml.j2"
  when: state == "started"

- name: Setup logrotate
  become: true
  blockinfile:
    path: "/etc/logrotate.d/traefik"
    block: |
      /{{ log_dir }}/*.log {
        compress
        create
        daily
        dateext
        dateformat -%Y%m%d
        missingok
        notifempty
        postrotate
          docker kill --signal="USR1" {{ container_name }}
        endscript
        rotate 5
      } 
    create: true

- name: Start traefik
  command: docker-compose -f traefik.yml up -d
  args:
    chdir: "{{ deploy_dir }}"
  when: deploy_state == "started"

- name: Stop traefik
  command: docker-compose -f traefik.yml down
  args:
    chdir: "{{ deploy_dir }}"
  when: state == "stopped"
